services:
  - type: web
    name: zocket-backend
    env: go
    plan: free
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: GO_VERSION
        value: 1.24.0
